// <auto-generated />
namespace Examentoezicht.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class DiscriminatorNotNull3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DiscriminatorNotNull3));
        
        string IMigrationMetadata.Id
        {
            get { return "201310250940088_DiscriminatorNotNull3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
